import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  date: 'hi'  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <h1> Start something new</h1>
      <h2> sunday today</h2>
      <h3> thinking about the next project idea /n enlight me with some good ideas please</h3>
      <h3> did some monotonic stack question and looked at the docker tutorial</h3>
      <h3> what did i do today, looked some monotonic question and all</h3>

      
    </html>
  )
}
